// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module dma_reg_top (
  input clk_i,
  input rst_ni,
  input  apb_req_t apb_req_i,
  output apb_rsp_t apb_rsp_o,
  output logic      apb_pready_o,
  // To HW
  output dma_reg_pkg::dma_reg2hw_t reg2hw, // Write
  input  dma_reg_pkg::dma_hw2reg_t hw2reg, // Read

  // Integrity check errors
  output logic intg_err_o
);

  import dma_reg_pkg::* ;
  import intf_pkg::*;

  localparam int AW = 6;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;



  // incoming payload check
  logic intg_err;
  assign intg_err = 1'b0;

  // also check for spurious write enables
  logic reg_we_err;
  logic [11:0] reg_we_check;
  prim_reg_we_check #(
    .OneHotWidth(12)
  ) u_prim_reg_we_check (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oh_i  (reg_we_check),
    .en_i  (reg_we && !addrmiss),
    .err_o (reg_we_err)
  );

  logic err_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      err_q <= '0;
    end else if (intg_err || reg_we_err) begin
      err_q <= 1'b1;
    end
  end

  // integrity error output is permanent and should be used for alert generation
  // register errors are transactional
  assign intg_err_o = err_q | intg_err | reg_we_err;

  // outgoing integrity generation

  apb_reg #(
    .DATA_WIDTH(DW),
    .ADDR_WIDTH(AW),
    .STRB_WIDTH(DBW),
    .REG_AWIDTH(AW)
  ) u_reg_if (
    .clk_i     (clk_i),
    .rst_ni    (rst_ni),
    .apb_req_i (apb_req_i),
    .apb_rsp_o (apb_rsp_o),
    .apb_pready_o (apb_pready_o),
    .wdata_o   (reg_wdata),
    .be_o      (reg_be),
    .ren_o     (reg_re),
    .wen_o     (reg_we),
    .addr_o    (reg_addr),
    .busy_i    (reg_busy),
    .rdata_i   (reg_rdata),
    .error_i   (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = addrmiss | wr_err | intg_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ctrl_we;
  logic ctrl_go_qs;
  logic ctrl_go_wd;
  logic ctrl_abort_qs;
  logic ctrl_abort_wd;
  logic [7:0] ctrl_max_burst_qs;
  logic [7:0] ctrl_max_burst_wd;
  logic status_re;
  logic [15:0] status_version_qs;
  logic status_done_qs;
  logic status_error_qs;
  logic desc_src_addr_0_we;
  logic [31:0] desc_src_addr_0_qs;
  logic [31:0] desc_src_addr_0_wd;
  logic desc_src_addr_1_we;
  logic [31:0] desc_src_addr_1_qs;
  logic [31:0] desc_src_addr_1_wd;
  logic desc_dst_addr_0_we;
  logic [31:0] desc_dst_addr_0_qs;
  logic [31:0] desc_dst_addr_0_wd;
  logic desc_dst_addr_1_we;
  logic [31:0] desc_dst_addr_1_qs;
  logic [31:0] desc_dst_addr_1_wd;
  logic desc_num_bytes_0_we;
  logic [31:0] desc_num_bytes_0_qs;
  logic [31:0] desc_num_bytes_0_wd;
  logic desc_num_bytes_1_we;
  logic [31:0] desc_num_bytes_1_qs;
  logic [31:0] desc_num_bytes_1_wd;
  logic desc_cfg_0_we;
  logic desc_cfg_0_read_mode_0_qs;
  logic desc_cfg_0_read_mode_0_wd;
  logic desc_cfg_0_write_mode_0_qs;
  logic desc_cfg_0_write_mode_0_wd;
  logic desc_cfg_0_enable_0_qs;
  logic desc_cfg_0_enable_0_wd;
  logic desc_cfg_1_we;
  logic desc_cfg_1_read_mode_1_qs;
  logic desc_cfg_1_read_mode_1_wd;
  logic desc_cfg_1_write_mode_1_qs;
  logic desc_cfg_1_write_mode_1_wd;
  logic desc_cfg_1_enable_1_qs;
  logic desc_cfg_1_enable_1_wd;
  logic err_addr_re;
  logic [31:0] err_addr_qs;
  logic err_stats_re;
  logic err_stats_err_type_qs;
  logic err_stats_err_src_qs;
  logic err_stats_err_trig_qs;

  // Register instances
  // R[ctrl]: V(False)
  //   F[go]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_go (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_go_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.go.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_go_qs)
  );

  //   F[abort]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_abort (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_abort_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.abort.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_abort_qs)
  );

  //   F[max_burst]: 9:2
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_ctrl_max_burst (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_max_burst_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.max_burst.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_max_burst_qs)
  );


  // R[status]: V(True)
  //   F[version]: 15:0
  prim_subreg_ext #(
    .DW    (16)
  ) u_status_version (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.version.d),
    .qre    (reg2hw.status.version.re),
    .qe     (),
    .q      (reg2hw.status.version.q),
    .ds     (),
    .qs     (status_version_qs)
  );

  //   F[done]: 16:16
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_done (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.done.d),
    .qre    (reg2hw.status.done.re),
    .qe     (),
    .q      (reg2hw.status.done.q),
    .ds     (),
    .qs     (status_done_qs)
  );

  //   F[error]: 17:17
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_error (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.error.d),
    .qre    (reg2hw.status.error.re),
    .qe     (),
    .q      (reg2hw.status.error.q),
    .ds     (),
    .qs     (status_error_qs)
  );


  // Subregister 0 of Multireg desc_src_addr
  // R[desc_src_addr_0]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_desc_src_addr_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_src_addr_0_we),
    .wd     (desc_src_addr_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_src_addr[0].q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_src_addr_0_qs)
  );


  // Subregister 1 of Multireg desc_src_addr
  // R[desc_src_addr_1]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_desc_src_addr_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_src_addr_1_we),
    .wd     (desc_src_addr_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_src_addr[1].q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_src_addr_1_qs)
  );


  // Subregister 0 of Multireg desc_dst_addr
  // R[desc_dst_addr_0]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_desc_dst_addr_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_dst_addr_0_we),
    .wd     (desc_dst_addr_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_dst_addr[0].q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_dst_addr_0_qs)
  );


  // Subregister 1 of Multireg desc_dst_addr
  // R[desc_dst_addr_1]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_desc_dst_addr_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_dst_addr_1_we),
    .wd     (desc_dst_addr_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_dst_addr[1].q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_dst_addr_1_qs)
  );


  // Subregister 0 of Multireg desc_num_bytes
  // R[desc_num_bytes_0]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_desc_num_bytes_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_num_bytes_0_we),
    .wd     (desc_num_bytes_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_num_bytes[0].q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_num_bytes_0_qs)
  );


  // Subregister 1 of Multireg desc_num_bytes
  // R[desc_num_bytes_1]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_desc_num_bytes_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_num_bytes_1_we),
    .wd     (desc_num_bytes_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_num_bytes[1].q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_num_bytes_1_qs)
  );


  // Subregister 0 of Multireg desc_cfg
  // R[desc_cfg_0]: V(False)
  //   F[read_mode_0]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_desc_cfg_0_read_mode_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_cfg_0_we),
    .wd     (desc_cfg_0_read_mode_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_cfg[0].read_mode.q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_cfg_0_read_mode_0_qs)
  );

  //   F[write_mode_0]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_desc_cfg_0_write_mode_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_cfg_0_we),
    .wd     (desc_cfg_0_write_mode_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_cfg[0].write_mode.q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_cfg_0_write_mode_0_qs)
  );

  //   F[enable_0]: 2:2
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_desc_cfg_0_enable_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_cfg_0_we),
    .wd     (desc_cfg_0_enable_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_cfg[0].enable.q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_cfg_0_enable_0_qs)
  );


  // Subregister 1 of Multireg desc_cfg
  // R[desc_cfg_1]: V(False)
  //   F[read_mode_1]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_desc_cfg_1_read_mode_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_cfg_1_we),
    .wd     (desc_cfg_1_read_mode_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_cfg[1].read_mode.q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_cfg_1_read_mode_1_qs)
  );

  //   F[write_mode_1]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_desc_cfg_1_write_mode_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_cfg_1_we),
    .wd     (desc_cfg_1_write_mode_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_cfg[1].write_mode.q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_cfg_1_write_mode_1_qs)
  );

  //   F[enable_1]: 2:2
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_desc_cfg_1_enable_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (desc_cfg_1_we),
    .wd     (desc_cfg_1_enable_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.desc_cfg[1].enable.q),
    .ds     (),

    // to register interface (read)
    .qs     (desc_cfg_1_enable_1_qs)
  );


  // R[err_addr]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_err_addr (
    .re     (err_addr_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.err_addr.d),
    .qre    (reg2hw.err_addr.re),
    .qe     (),
    .q      (reg2hw.err_addr.q),
    .ds     (),
    .qs     (err_addr_qs)
  );


  // R[err_stats]: V(True)
  //   F[err_type]: 0:0
  prim_subreg_ext #(
    .DW    (1)
  ) u_err_stats_err_type (
    .re     (err_stats_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.err_stats.err_type.d),
    .qre    (reg2hw.err_stats.err_type.re),
    .qe     (),
    .q      (reg2hw.err_stats.err_type.q),
    .ds     (),
    .qs     (err_stats_err_type_qs)
  );

  //   F[err_src]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_err_stats_err_src (
    .re     (err_stats_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.err_stats.err_src.d),
    .qre    (reg2hw.err_stats.err_src.re),
    .qe     (),
    .q      (reg2hw.err_stats.err_src.q),
    .ds     (),
    .qs     (err_stats_err_src_qs)
  );

  //   F[err_trig]: 2:2
  prim_subreg_ext #(
    .DW    (1)
  ) u_err_stats_err_trig (
    .re     (err_stats_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.err_stats.err_trig.d),
    .qre    (reg2hw.err_stats.err_trig.re),
    .qe     (),
    .q      (reg2hw.err_stats.err_trig.q),
    .ds     (),
    .qs     (err_stats_err_trig_qs)
  );



  logic [11:0] addr_hit;
  always_comb begin
    addr_hit[ 0] = (reg_addr == DMA_CTRL_OFFSET);
    addr_hit[ 1] = (reg_addr == DMA_STATUS_OFFSET);
    addr_hit[ 2] = (reg_addr == DMA_DESC_SRC_ADDR_0_OFFSET);
    addr_hit[ 3] = (reg_addr == DMA_DESC_SRC_ADDR_1_OFFSET);
    addr_hit[ 4] = (reg_addr == DMA_DESC_DST_ADDR_0_OFFSET);
    addr_hit[ 5] = (reg_addr == DMA_DESC_DST_ADDR_1_OFFSET);
    addr_hit[ 6] = (reg_addr == DMA_DESC_NUM_BYTES_0_OFFSET);
    addr_hit[ 7] = (reg_addr == DMA_DESC_NUM_BYTES_1_OFFSET);
    addr_hit[ 8] = (reg_addr == DMA_DESC_CFG_0_OFFSET);
    addr_hit[ 9] = (reg_addr == DMA_DESC_CFG_1_OFFSET);
    addr_hit[10] = (reg_addr == DMA_ERR_ADDR_OFFSET);
    addr_hit[11] = (reg_addr == DMA_ERR_STATS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(DMA_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(DMA_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(DMA_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(DMA_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(DMA_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(DMA_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(DMA_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(DMA_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(DMA_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(DMA_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(DMA_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(DMA_PERMIT[11] & ~reg_be)))));
  end

  // Generate write-enables
  assign ctrl_we = addr_hit[0] & reg_we & !reg_error;

  assign ctrl_go_wd = reg_wdata[0];

  assign ctrl_abort_wd = reg_wdata[1];

  assign ctrl_max_burst_wd = reg_wdata[9:2];
  assign status_re = addr_hit[1] & reg_re & !reg_error;
  assign desc_src_addr_0_we = addr_hit[2] & reg_we & !reg_error;

  assign desc_src_addr_0_wd = reg_wdata[31:0];
  assign desc_src_addr_1_we = addr_hit[3] & reg_we & !reg_error;

  assign desc_src_addr_1_wd = reg_wdata[31:0];
  assign desc_dst_addr_0_we = addr_hit[4] & reg_we & !reg_error;

  assign desc_dst_addr_0_wd = reg_wdata[31:0];
  assign desc_dst_addr_1_we = addr_hit[5] & reg_we & !reg_error;

  assign desc_dst_addr_1_wd = reg_wdata[31:0];
  assign desc_num_bytes_0_we = addr_hit[6] & reg_we & !reg_error;

  assign desc_num_bytes_0_wd = reg_wdata[31:0];
  assign desc_num_bytes_1_we = addr_hit[7] & reg_we & !reg_error;

  assign desc_num_bytes_1_wd = reg_wdata[31:0];
  assign desc_cfg_0_we = addr_hit[8] & reg_we & !reg_error;

  assign desc_cfg_0_read_mode_0_wd = reg_wdata[0];

  assign desc_cfg_0_write_mode_0_wd = reg_wdata[1];

  assign desc_cfg_0_enable_0_wd = reg_wdata[2];
  assign desc_cfg_1_we = addr_hit[9] & reg_we & !reg_error;

  assign desc_cfg_1_read_mode_1_wd = reg_wdata[0];

  assign desc_cfg_1_write_mode_1_wd = reg_wdata[1];

  assign desc_cfg_1_enable_1_wd = reg_wdata[2];
  assign err_addr_re = addr_hit[10] & reg_re & !reg_error;
  assign err_stats_re = addr_hit[11] & reg_re & !reg_error;

  // Assign write-enables to checker logic vector.
  always_comb begin
    reg_we_check[0] = ctrl_we;
    reg_we_check[1] = 1'b0;
    reg_we_check[2] = desc_src_addr_0_we;
    reg_we_check[3] = desc_src_addr_1_we;
    reg_we_check[4] = desc_dst_addr_0_we;
    reg_we_check[5] = desc_dst_addr_1_we;
    reg_we_check[6] = desc_num_bytes_0_we;
    reg_we_check[7] = desc_num_bytes_1_we;
    reg_we_check[8] = desc_cfg_0_we;
    reg_we_check[9] = desc_cfg_1_we;
    reg_we_check[10] = 1'b0;
    reg_we_check[11] = 1'b0;
  end

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = ctrl_go_qs;
        reg_rdata_next[1] = ctrl_abort_qs;
        reg_rdata_next[9:2] = ctrl_max_burst_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[15:0] = status_version_qs;
        reg_rdata_next[16] = status_done_qs;
        reg_rdata_next[17] = status_error_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = desc_src_addr_0_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = desc_src_addr_1_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = desc_dst_addr_0_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = desc_dst_addr_1_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = desc_num_bytes_0_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = desc_num_bytes_1_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[0] = desc_cfg_0_read_mode_0_qs;
        reg_rdata_next[1] = desc_cfg_0_write_mode_0_qs;
        reg_rdata_next[2] = desc_cfg_0_enable_0_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[0] = desc_cfg_1_read_mode_1_qs;
        reg_rdata_next[1] = desc_cfg_1_write_mode_1_qs;
        reg_rdata_next[2] = desc_cfg_1_enable_1_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[31:0] = err_addr_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[0] = err_stats_err_type_qs;
        reg_rdata_next[1] = err_stats_err_src_qs;
        reg_rdata_next[2] = err_stats_err_trig_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)


  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)

endmodule
