// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package dma_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;

  // Number of registers for every interface
  parameter int NumRegs = 12;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [7:0] q;
    } max_burst;
    struct packed {
      logic  q;
    } abort;
    struct packed {
      logic  q;
    } go;
  } dma_reg2hw_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic  q;
      logic        re;
    } error;
    struct packed {
      logic  q;
      logic        re;
    } done;
    struct packed {
      logic [15:0] q;
      logic        re;
    } version;
  } dma_reg2hw_status_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_desc_src_addr_mreg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_desc_dst_addr_mreg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_desc_num_bytes_mreg_t;

  typedef struct packed {
    struct packed {
      logic  q;
    } enable;
    struct packed {
      logic  q;
    } write_mode;
    struct packed {
      logic  q;
    } read_mode;
  } dma_reg2hw_desc_cfg_mreg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        re;
  } dma_reg2hw_err_addr_reg_t;

  typedef struct packed {
    struct packed {
      logic  q;
      logic        re;
    } err_trig;
    struct packed {
      logic  q;
      logic        re;
    } err_src;
    struct packed {
      logic  q;
      logic        re;
    } err_type;
  } dma_reg2hw_err_stats_reg_t;

  typedef struct packed {
    struct packed {
      logic  d;
    } error;
    struct packed {
      logic  d;
    } done;
    struct packed {
      logic [15:0] d;
    } version;
  } dma_hw2reg_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } dma_hw2reg_err_addr_reg_t;

  typedef struct packed {
    struct packed {
      logic  d;
    } err_trig;
    struct packed {
      logic  d;
    } err_src;
    struct packed {
      logic  d;
    } err_type;
  } dma_hw2reg_err_stats_reg_t;

  // Register -> HW type
  typedef struct packed {
    dma_reg2hw_ctrl_reg_t ctrl; // [267:258]
    dma_reg2hw_status_reg_t status; // [257:237]
    dma_reg2hw_desc_src_addr_mreg_t [1:0] desc_src_addr; // [236:173]
    dma_reg2hw_desc_dst_addr_mreg_t [1:0] desc_dst_addr; // [172:109]
    dma_reg2hw_desc_num_bytes_mreg_t [1:0] desc_num_bytes; // [108:45]
    dma_reg2hw_desc_cfg_mreg_t [1:0] desc_cfg; // [44:39]
    dma_reg2hw_err_addr_reg_t err_addr; // [38:6]
    dma_reg2hw_err_stats_reg_t err_stats; // [5:0]
  } dma_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    dma_hw2reg_status_reg_t status; // [52:35]
    dma_hw2reg_err_addr_reg_t err_addr; // [34:3]
    dma_hw2reg_err_stats_reg_t err_stats; // [2:0]
  } dma_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] DMA_CTRL_OFFSET = 6'h 0;
  parameter logic [BlockAw-1:0] DMA_STATUS_OFFSET = 6'h 4;
  parameter logic [BlockAw-1:0] DMA_DESC_SRC_ADDR_0_OFFSET = 6'h 8;
  parameter logic [BlockAw-1:0] DMA_DESC_SRC_ADDR_1_OFFSET = 6'h c;
  parameter logic [BlockAw-1:0] DMA_DESC_DST_ADDR_0_OFFSET = 6'h 10;
  parameter logic [BlockAw-1:0] DMA_DESC_DST_ADDR_1_OFFSET = 6'h 14;
  parameter logic [BlockAw-1:0] DMA_DESC_NUM_BYTES_0_OFFSET = 6'h 18;
  parameter logic [BlockAw-1:0] DMA_DESC_NUM_BYTES_1_OFFSET = 6'h 1c;
  parameter logic [BlockAw-1:0] DMA_DESC_CFG_0_OFFSET = 6'h 20;
  parameter logic [BlockAw-1:0] DMA_DESC_CFG_1_OFFSET = 6'h 24;
  parameter logic [BlockAw-1:0] DMA_ERR_ADDR_OFFSET = 6'h 28;
  parameter logic [BlockAw-1:0] DMA_ERR_STATS_OFFSET = 6'h 2c;

  // Reset values for hwext registers and their fields
  parameter logic [17:0] DMA_STATUS_RESVAL = 18'h 0;
  parameter logic [31:0] DMA_ERR_ADDR_RESVAL = 32'h 0;
  parameter logic [2:0] DMA_ERR_STATS_RESVAL = 3'h 0;

  // Register index
  typedef enum int {
    DMA_CTRL,
    DMA_STATUS,
    DMA_DESC_SRC_ADDR_0,
    DMA_DESC_SRC_ADDR_1,
    DMA_DESC_DST_ADDR_0,
    DMA_DESC_DST_ADDR_1,
    DMA_DESC_NUM_BYTES_0,
    DMA_DESC_NUM_BYTES_1,
    DMA_DESC_CFG_0,
    DMA_DESC_CFG_1,
    DMA_ERR_ADDR,
    DMA_ERR_STATS
  } dma_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] DMA_PERMIT [12] = '{
    4'b 0011, // index[ 0] DMA_CTRL
    4'b 0111, // index[ 1] DMA_STATUS
    4'b 1111, // index[ 2] DMA_DESC_SRC_ADDR_0
    4'b 1111, // index[ 3] DMA_DESC_SRC_ADDR_1
    4'b 1111, // index[ 4] DMA_DESC_DST_ADDR_0
    4'b 1111, // index[ 5] DMA_DESC_DST_ADDR_1
    4'b 1111, // index[ 6] DMA_DESC_NUM_BYTES_0
    4'b 1111, // index[ 7] DMA_DESC_NUM_BYTES_1
    4'b 0001, // index[ 8] DMA_DESC_CFG_0
    4'b 0001, // index[ 9] DMA_DESC_CFG_1
    4'b 1111, // index[10] DMA_ERR_ADDR
    4'b 0001  // index[11] DMA_ERR_STATS
  };

endpackage
