#!/usr/bin/env python3
"""Check mechanically enforceable Axon repository policies.

The initial pre-commit hook is manual-only while legacy RTL is normalized.
This checker intentionally uses only Python's standard library.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
POLICY_SUFFIXES = {".sv", ".svh", ".core"}


@dataclass(frozen=True)
class Finding:
    path: Path
    line: int
    message: str


def git_paths(args: list[str]) -> set[Path]:
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return {Path(line) for line in result.stdout.splitlines() if line}


def default_changed_paths() -> list[Path]:
    paths = set()
    paths |= git_paths(["diff", "--name-only", "--diff-filter=ACMR"])
    paths |= git_paths(
        ["diff", "--cached", "--name-only", "--diff-filter=ACMR"]
    )
    paths |= git_paths(["ls-files", "--others", "--exclude-standard"])
    return sorted(paths)


def all_policy_paths() -> list[Path]:
    return sorted(
        path.relative_to(REPO_ROOT)
        for path in REPO_ROOT.rglob("*")
        if path.is_file()
        and path.suffix in POLICY_SUFFIXES
        and ".git" not in path.parts
        and "build" not in path.parts
    )


def line_number(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def check_text_hygiene(path: Path, text: str) -> list[Finding]:
    findings = []
    for number, line in enumerate(text.splitlines(), 1):
        if "\t" in line:
            findings.append(Finding(path, number, "tab character; use spaces"))
        if line.rstrip() != line:
            findings.append(Finding(path, number, "trailing whitespace"))
    return findings


def is_generated(text: str) -> bool:
    head = "\n".join(text.splitlines()[:12]).lower()
    return "auto-generated" in head or "generated by" in head


def check_systemverilog(path: Path, text: str) -> list[Finding]:
    if "axon-policy-allow: legacy-file" in text:
        if "legacy" in path.parts:
            return []
        return [Finding(
            path,
            1,
            "legacy-file allowance is valid only under a legacy/ directory",
        )]

    findings = check_text_hygiene(path, text)
    if is_generated(text):
        return findings

    allowed_rules = set(re.findall(r"axon-policy-allow:\s*([a-z-]+)", text))

    for match in re.finditer(
        r"always_ff\s*@\s*\([^)]*\b(?:or|,)\s*negedge\s+rst_[a-z0-9_]*n[io]?\b",
        text,
        re.IGNORECASE | re.MULTILINE,
    ):
        findings.append(
            Finding(
                path,
                line_number(text, match.start()),
                "asynchronous reset event; Axon reset is synchronous active-low",
            )
        )

    if "legacy-always" not in allowed_rules:
        for match in re.finditer(r"(?m)^\s*always\s*@", text):
            findings.append(
                Finding(
                    path,
                    line_number(text, match.start()),
                    "legacy always block; use always_comb, always_ff, or always_latch",
                )
            )

    modules = re.findall(r"(?m)^\s*module\s+([a-zA-Z_][a-zA-Z0-9_$]*)", text)
    if modules and path.stem not in modules:
        findings.append(
            Finding(
                path,
                1,
                f"filename stem does not match a module name ({', '.join(modules)})",
            )
        )

    for match in re.finditer(
        r"(?m)^\s*(?:parameter|localparam)\s+(?:(?:int|integer|bit|logic|reg|[a-zA-Z_]\w*(?:::\w+)?)\b(?:\s+(?:unsigned|signed))?(?:\s*\[[^\]]+\])?\s+)?([a-zA-Z_]\w*)\s*=",
        text,
    ):
        name = match.group(1)
        if name.startswith("__"):
            continue
        if not re.fullmatch(r"[A-Z][a-zA-Z0-9]*", name):
            findings.append(
                Finding(
                    path,
                    line_number(text, match.start()),
                    f"parameter/localparam '{name}' must use UpperCamelCase",
                )
            )

    return findings


def check_core(path: Path, text: str) -> list[Finding]:
    findings = check_text_hygiene(path, text)
    name_match = re.search(r'(?m)^name:\s*["\']?([^"\'\s]+)', text)
    if not name_match:
        findings.append(Finding(path, 1, "FuseSoC core has no name field"))
    else:
        vlnv = name_match.group(1)
        parts = vlnv.split(":")
        if len(parts) != 4 or any(not part for part in parts):
            findings.append(
                Finding(path, line_number(text, name_match.start()),
                        f"core name '{vlnv}' must be a complete vendor:library:name:version VLNV")
            )
        elif parts[0] != "axon":
            findings.append(
                Finding(path, line_number(text, name_match.start()),
                        f"core vendor '{parts[0]}' must be 'axon'")
            )

    for match in re.finditer(r"(?m)^\s*-\s+(lowrisc:[^\s#]+)", text):
        findings.append(
            Finding(
                path,
                line_number(text, match.start()),
                f"legacy FuseSoC dependency '{match.group(1)}'; migrate to axon namespace",
            )
        )
    return findings


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", type=Path,
                        help="files to check; defaults to changed and untracked files")
    parser.add_argument("--all", action="store_true",
                        help="check every policy-controlled file")
    parser.add_argument("--warn-only", action="store_true",
                        help="print findings but return success during cleanup")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.all and args.paths:
        raise SystemExit("--all and explicit paths are mutually exclusive")

    paths = all_policy_paths() if args.all else (
        args.paths if args.paths else default_changed_paths()
    )
    paths = sorted({path if not path.is_absolute() else path.relative_to(REPO_ROOT)
                    for path in paths})

    findings: list[Finding] = []
    checked = 0
    for path in paths:
        if path.suffix not in POLICY_SUFFIXES:
            continue
        absolute = REPO_ROOT / path
        if not absolute.is_file():
            continue
        text = absolute.read_text(encoding="utf-8")
        checked += 1
        if path.suffix in {".sv", ".svh"}:
            findings.extend(check_systemverilog(path, text))
        elif path.suffix == ".core":
            findings.extend(check_core(path, text))

    for finding in sorted(findings, key=lambda item: (str(item.path), item.line, item.message)):
        print(f"{finding.path}:{finding.line}: {finding.message}")

    summary = f"Axon policy check: {checked} file(s), {len(findings)} finding(s)"
    print(summary)
    return 0 if not findings or args.warn_only else 1


if __name__ == "__main__":
    sys.exit(main())
